In [1]:
import cvxpy as cp
import numpy as np

In [29]:
np.random.seed(1)

A = np.random.randn(10, 10)
r = np.random.randn(10, 1)*0
r = np.zeros((10,1))
Sigma = A.T @ A
w = cp.Variable(shape=(10, 1), name="x")

obj = cp.Minimize(cp.quad_form(w, Sigma) - r.T @ w)
constraints = [cp.sum(w) == 1]
problem = cp.Problem(obj, constraints)
problem.solve()

0.05722493304064699

In [31]:
w.value

array([[ 0.24802866],
       [ 0.03429784],
       [ 0.35719376],
       [ 0.14852699],
       [-0.27949104],
       [-0.01565613],
       [ 0.11801894],
       [-0.0297881 ],
       [ 0.18537017],
       [ 0.23349891]])

In [25]:
w.value

array([[ 0.24802866],
       [ 0.03429784],
       [ 0.35719376],
       [ 0.14852699],
       [-0.27949104],
       [-0.01565613],
       [ 0.11801894],
       [-0.0297881 ],
       [ 0.18537017],
       [ 0.23349891]])

In [26]:
obj = cp.Minimize(cp.quad_form(w, Sigma))
constraints = [cp.sum(w) == 1]
problem = cp.Problem(obj, constraints)
problem.solve()

0.05722493304064699

In [27]:
w.value

array([[ 0.24802866],
       [ 0.03429784],
       [ 0.35719376],
       [ 0.14852699],
       [-0.27949104],
       [-0.01565613],
       [ 0.11801894],
       [-0.0297881 ],
       [ 0.18537017],
       [ 0.23349891]])